pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()

    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }

        maven {
            url "https://raw.githubusercontent.com/didit-protocol/sdk-android/main/repository"
        }
    }
}

rootProject.name = "Nelsen Savannah"
include ':app'
include ':CustomSnackbarLib'
include ':overlapimagelistview'