plugins {
    alias(libs.plugins.android.application)
    id 'org.jetbrains.kotlin.android'
    id("com.google.gms.google-services")
    id("com.google.devtools.ksp")
}
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def webClientId = localProperties.getProperty('WEB_CLIENT_ID', '"default_web_client_id"')
def facebookAppId = localProperties.getProperty('FACEBOOK_APP_ID')
def facebookClientToken = localProperties.getProperty('FACEBOOK_CLIENT_TOKEN')
def fbLoginScheme = localProperties.getProperty('FB_LOGIN_PROTOCOL_SCHEME')

android {
    namespace 'com.app.nisisiafrica'
    compileSdk 35

    defaultConfig {
        applicationId "com.app.nisisiafrica"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"

//        buildConfigField "String", "WEB_CLIENT_ID", "\"${WEB_CLIENT_ID}\""
        buildConfigField "String", "WEB_CLIENT_ID", webClientId
        resValue "string", "facebook_app_id", "\"${facebookAppId}\""
        resValue "string", "facebook_client_token", "\"${facebookClientToken}\""
        resValue "string", "fb_login_protocol_scheme", "\"${fbLoginScheme}\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    ksp {
        arg("room.schemaLocation", "$projectDir/schemas")
    }

    buildFeatures {
        viewBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation libs.lifecycle.viewmodel
    implementation libs.lifecycle.livedata
    implementation libs.lifecycle.extensions
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.play.services.auth
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    implementation libs.gson

    //ui
//    implementation project(':liquid_swipe')
    implementation 'com.github.vipulasri:timelineview:1.1.5'
    implementation("com.kizitonwose.calendar:view:2.8.0")
    implementation 'com.github.ismaeldivita:chip-navigation-bar:1.4.0'
    implementation project(':CustomSnackbarLib')
    implementation project(':overlapimagelistview')
    implementation project (':fabtobottomnavigation')

    implementation libs.dotsindicator
    implementation libs.core.splashscreen
    implementation libs.circleimageview
    implementation libs.swiperefreshlayout
    implementation libs.glide
    annotationProcessor libs.compiler


    //firebase
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.analytics)
    implementation libs.firebase.auth
    implementation libs.firebase.storage
    implementation libs.firebase.database
    //google cloud auth
    implementation libs.credentials
    implementation libs.credentials.play.services.auth
    implementation libs.googleid.v111

    //facebook Auth
    implementation libs.facebook.login

    // Google Identity Services
    implementation libs.play.services.auth

    // For Identity API
    implementation libs.play.services.identity

    //Room db
    def room_version = "2.7.1"
    implementation "androidx.room:room-runtime:$room_version"
    ksp("androidx.room:room-compiler:$room_version")
    annotationProcessor "androidx.room:room-compiler:$room_version"
    implementation("androidx.room:room-ktx:$room_version")
    implementation("io.reactivex.rxjava3:rxandroid:3.0.2")
    implementation("androidx.room:room-rxjava3:$room_version")
//    implementation("io.reactivex.rxjava3:rxjava:3.1.8")
//    implementation("io.reactivex.rxjava3:rxandroid:3.0.2")
    implementation("androidx.room:room-paging:$room_version")
}