/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as TourismRouteImport } from './routes/tourism'
import { Route as LearningTrackIdRouteImport } from './routes/learning.$trackId'
import { Route as LearningCertificatesRouteImport } from './routes/learning.certificates'
import { Route as LearningCourseworkRouteImport } from './routes/learning.coursework'
import { Route as LearningTrackIdLessonLessonIdRouteImport } from './routes/learning.$trackId.lesson.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismRoute = TourismRouteImport.update({
  id: '/tourism',
  path: '/tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningTrackIdRoute = LearningTrackIdRouteImport.update({
  id: '/$trackId',
  path: '/$trackId',
  getParentRoute: () => LearningRoute,
} as any)
const LearningCertificatesRoute = LearningCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => LearningRoute,
} as any)
const LearningCourseworkRoute = LearningCourseworkRouteImport.update({
  id: '/coursework',
  path: '/coursework',
  getParentRoute: () => LearningRoute,
} as any)
const LearningTrackIdLessonLessonIdRoute =
  LearningTrackIdLessonLessonIdRouteImport.update({
    id: '/lesson/$lessonId',
    path: '/lesson/$lessonId',
    getParentRoute: () => LearningTrackIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/invest': typeof InvestRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/school': typeof SchoolRoute
  '/teach': typeof TeachRoute
  '/tourism': typeof TourismRoute
  '/learning/$trackId': typeof LearningTrackIdRouteWithChildren
  '/learning/certificates': typeof LearningCertificatesRoute
  '/learning/coursework': typeof LearningCourseworkRoute
  '/learning/$trackId/lesson/$lessonId': typeof LearningTrackIdLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/invest': typeof InvestRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/school': typeof SchoolRoute
  '/teach': typeof TeachRoute
  '/tourism': typeof TourismRoute
  '/learning/$trackId': typeof LearningTrackIdRouteWithChildren
  '/learning/certificates': typeof LearningCertificatesRoute
  '/learning/coursework': typeof LearningCourseworkRoute
  '/learning/$trackId/lesson/$lessonId': typeof LearningTrackIdLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/invest': typeof InvestRoute
  '/learning': typeof LearningRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/profile': typeof ProfileRoute
  '/programs': typeof ProgramsRoute
  '/school': typeof SchoolRoute
  '/teach': typeof TeachRoute
  '/tourism': typeof TourismRoute
  '/learning/$trackId': typeof LearningTrackIdRouteWithChildren
  '/learning/certificates': typeof LearningCertificatesRoute
  '/learning/coursework': typeof LearningCourseworkRoute
  '/learning/$trackId/lesson/$lessonId': typeof LearningTrackIdLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blogs'
    | '/contact'
    | '/events'
    | '/invest'
    | '/learning'
    | '/login'
    | '/media'
    | '/profile'
    | '/programs'
    | '/school'
    | '/teach'
    | '/tourism'
    | '/learning/$trackId'
    | '/learning/certificates'
    | '/learning/coursework'
    | '/learning/$trackId/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/blogs'
    | '/contact'
    | '/events'
    | '/invest'
    | '/learning'
    | '/login'
    | '/media'
    | '/profile'
    | '/programs'
    | '/school'
    | '/teach'
    | '/tourism'
    | '/learning/$trackId'
    | '/learning/certificates'
    | '/learning/coursework'
    | '/learning/$trackId/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blogs'
    | '/contact'
    | '/events'
    | '/invest'
    | '/learning'
    | '/login'
    | '/media'
    | '/profile'
    | '/programs'
    | '/school'
    | '/teach'
    | '/tourism'
    | '/learning/$trackId'
    | '/learning/certificates'
    | '/learning/coursework'
    | '/learning/$trackId/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  InvestRoute: typeof InvestRoute
  LearningRoute: typeof LearningRouteWithChildren
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  ProfileRoute: typeof ProfileRoute
  ProgramsRoute: typeof ProgramsRoute
  SchoolRoute: typeof SchoolRoute
  TeachRoute: typeof TeachRoute
  TourismRoute: typeof TourismRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourism': {
      id: '/tourism'
      path: '/tourism'
      fullPath: '/tourism'
      preLoaderRoute: typeof TourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning/$trackId': {
      id: '/learning/$trackId'
      path: '/$trackId'
      fullPath: '/learning/$trackId'
      preLoaderRoute: typeof LearningTrackIdRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/certificates': {
      id: '/learning/certificates'
      path: '/certificates'
      fullPath: '/learning/certificates'
      preLoaderRoute: typeof LearningCertificatesRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/coursework': {
      id: '/learning/coursework'
      path: '/coursework'
      fullPath: '/learning/coursework'
      preLoaderRoute: typeof LearningCourseworkRouteImport
      parentRoute: typeof LearningRoute
    }
    '/learning/$trackId/lesson/$lessonId': {
      id: '/learning/$trackId/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/learning/$trackId/lesson/$lessonId'
      preLoaderRoute: typeof LearningTrackIdLessonLessonIdRouteImport
      parentRoute: typeof LearningTrackIdRoute
    }
  }
}

interface LearningTrackIdRouteChildren {
  LearningTrackIdLessonLessonIdRoute: typeof LearningTrackIdLessonLessonIdRoute
}

const LearningTrackIdRouteChildren: LearningTrackIdRouteChildren = {
  LearningTrackIdLessonLessonIdRoute: LearningTrackIdLessonLessonIdRoute,
}

const LearningTrackIdRouteWithChildren = LearningTrackIdRoute._addFileChildren(
  LearningTrackIdRouteChildren,
)

interface LearningRouteChildren {
  LearningTrackIdRoute: typeof LearningTrackIdRouteWithChildren
  LearningCertificatesRoute: typeof LearningCertificatesRoute
  LearningCourseworkRoute: typeof LearningCourseworkRoute
}

const LearningRouteChildren: LearningRouteChildren = {
  LearningTrackIdRoute: LearningTrackIdRouteWithChildren,
  LearningCertificatesRoute: LearningCertificatesRoute,
  LearningCourseworkRoute: LearningCourseworkRoute,
}

const LearningRouteWithChildren = LearningRoute._addFileChildren(
  LearningRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  InvestRoute: InvestRoute,
  LearningRoute: LearningRouteWithChildren,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  ProfileRoute: ProfileRoute,
  ProgramsRoute: ProgramsRoute,
  SchoolRoute: SchoolRoute,
  TeachRoute: TeachRoute,
  TourismRoute: TourismRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
